services:
  todo_list_db:
    image: postgres
    container_name: todo_list_db
    restart: always
    ports:
      - '3123:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo_list